version: '3.1'

services:

  tgbot1:
    container_name: in_support_max
    build: .
    volumes:
      - .:/src
    command: python app.py
    restart: always
    network_mode: "mysql_network_max"
    environment:
      TZ: "Europe/Moscow"
    env_file:
      - ".env"
