version: '3.1'

services:

#    network_mode: "docker_mysql_default"

  tgbot1:
    container_name: in_support_1c
    build: .
    volumes:
      - .:/src
    command: python app.py
    restart: always
    network_mode: "docker_mysql_default"

    env_file:
      - ".env"
